name: Release

on:
  push:
    tags:
      - 'v*'   # 當你 push 例如 v1.0、v2.1 時會觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create release package
        run: |
          mkdir dist
          zip -r dist/daily-tasks-tracker.zip . -x "*.git*" "__pycache__/*"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/daily-tasks-tracker.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}